name: release

on:
  push:
    branches:
      - main
      # TESTING: Uncomment the line below to allow releases from the current branch
      # This makes it easy to test semantic release on any branch.
      # To disable, comment out this line.
      - semantic-release
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual release)'
        required: false
        default: false
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run semantic release
        uses: python-semantic-release/python-semantic-release@v10.5.3
        with:
          github_token: ${GITHUB_TOKEN}
          # TODO: come back to figuring how to support dry-run mode
          # no_operation_mode: ${{ github.event.inputs.dry_run || false }}
          no_operation_mode: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
